[buildPlans.NxtFont]
family = "NxtFont"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.NxtFont.variants.design]
one = "base-long-top-serif"
three = "flat-top-serifless"
four = "open-non-crossing-serifless"
six = "open-contour"
seven = "bend-serifless-crossbar"
nine = "open-contour"
zero = "slashed"
capital-k = "straight-bottom-right-serifed"
capital-q = "crossing-baseline"
capital-w = "straight-almost-flat-top-motion-serifed"
capital-z = "straight-serifless-with-crossbar"
f = "tailed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifless"
k = "straight-bottom-right-serifed"
l = "serifed-diagonal-tailed"
q = "top-cut-diagonal-tailed-serifless"
t = "diagonal-tailed"
x = "semi-chancery-curly-serifless"
y = "cursive-motion-serifed"
z = "straight-serifless-with-crossbar"
lower-lambda = "tailed-turn"
number-sign = "slanted-tall"
at = "compact"
dollar = "slanted-through"
percent = "rings-continuous-slash"

[buildPlans.NxtFont.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.NxtFont.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.NxtFont.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.NxtFont.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.NxtFont.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.NxtFont.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.NxtFont.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
